version: '3'

tasks:
  build:
    envs:
      - GO111MODULE=on
    cmds:
      - go run build/ci.go install ./cmd/geth
  run:
    dir: ./build/bin
    cmds:
      - ./geth --datadir ../../deploy/node1/data --nodiscover   --http --http.addr localhost --http.port 8546 --unlock 0x1Cb750eddc261055589D9fE2DbF75cE013Df2Aa9 --mine --miner.etherbase=0x1Cb750eddc261055589D9fE2DbF75cE013Df2Aa9 --allow-insecure-unlock --password ../../deploy/node1/password --http.api eth,net,web3,debug
  connect:
    dir: ./build/bin
    cmds:
      - ./geth attach --datadir ../../deploy/node1/data
  init:
    dir: ./build/bin
    cmds:
      - ./geth --datadir ../../deploy/node1/data init ../../deploy/node1/genesis.json
